import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";

 

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl-PL">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
