import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { pool } from "@/lib/db";
import { UserAccount } from "@/components/UserAccount";
import { RefereeMatchesModal } from "@/components/RefereeMatchesModal";
import { RefereeGroupTableModal } from "@/components/RefereeGroupTableModal";

type MatchRow={id:string;pitch_name:string;group_name:string;start_time:Date;end_time:Date|null;home_score:number;away_score:number;status:"scheduled"|"live"|"finished"|"break";home_name:string;away_name:string;home_logo:string|null;away_logo:string|null};
async function referee(){const session=await auth();if(!session?.user||session.user.role!=="REFEREE")redirect("/");return session;}
async function finishMatch(data:FormData){"use server";const session=await referee();const matchId=String(data.get("matchId")??"");if(!matchId)return;await pool.query(`UPDATE matches m SET status='finished',updated_at=now() FROM tournament_referees tr WHERE m.id=$1 AND tr.user_id=$2 AND tr.tournament_id=m.tournament_id AND ((tr.pitch_id IS NOT NULL AND tr.pitch_id=m.pitch_id) OR (tr.group_id IS NOT NULL AND tr.group_id=m.group_id))`,[matchId,session.user.id]);revalidatePath("/referee");revalidatePath("/");}
const clock=(date:Date|null)=>date?date.toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Warsaw"}):"--:--";

export default async function RefereePage(){const session=await referee();await pool.query(`ALTER TABLE tournament_referees ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES users(id) ON DELETE CASCADE`);await pool.query(`ALTER TABLE tournament_referees ADD COLUMN IF NOT EXISTS pitch_id uuid REFERENCES pitches(id) ON DELETE CASCADE`);await pool.query(`ALTER TABLE tournament_referees ADD COLUMN IF NOT EXISTS group_id uuid REFERENCES groups(id) ON DELETE CASCADE`);
  const result=await pool.query<MatchRow>(`SELECT DISTINCT m.id,p.name pitch_name,g.name group_name,m.start_time,m.end_time,m.home_score,m.away_score,m.status,ht.name home_name,at.name away_name,ht.logo_url home_logo,at.logo_url away_logo FROM matches m JOIN pitches p ON p.id=m.pitch_id JOIN groups g ON g.id=m.group_id JOIN teams ht ON ht.id=m.home_team_id JOIN teams at ON at.id=m.away_team_id JOIN tournament_referees tr ON tr.tournament_id=m.tournament_id AND tr.user_id=$1 AND ((tr.pitch_id IS NOT NULL AND tr.pitch_id=m.pitch_id) OR (tr.group_id IS NOT NULL AND tr.group_id=m.group_id)) ORDER BY m.start_time`,[session.user.id]);
  const tournamentMatches=await pool.query<MatchRow>(`SELECT DISTINCT m.id,p.name pitch_name,g.name group_name,m.start_time,m.end_time,m.home_score,m.away_score,m.status,ht.name home_name,at.name away_name,ht.logo_url home_logo,at.logo_url away_logo FROM matches m JOIN pitches p ON p.id=m.pitch_id JOIN groups g ON g.id=m.group_id JOIN teams ht ON ht.id=m.home_team_id JOIN teams at ON at.id=m.away_team_id WHERE m.tournament_id IN (SELECT tournament_id FROM tournament_referees WHERE user_id=$1) ORDER BY g.name,m.start_time`,[session.user.id]);
  const matches=result.rows;const active=matches.find(m=>m.status==="live"||m.status==="break")??matches.find(m=>m.status==="scheduled")??null;const upcoming=matches.filter(m=>m.status==="scheduled"&&m.id!==active?.id);const next=upcoming[0]??null;const previous=[...matches].reverse().find(m=>m.status==="finished")??null;
  const upcomingModal=upcoming.map(match=>({id:match.id,teams:`${match.home_name} × ${match.away_name}`,time:`${clock(match.start_time)}-${clock(match.end_time)}`}));
  const finishedModal=matches.filter(match=>match.status==="finished").reverse().map(match=>({id:match.id,teams:`${match.home_name} × ${match.away_name}`,score:`${match.home_score}:${match.away_score}`,time:`${clock(match.start_time)}-${clock(match.end_time)}`}));
  const grouped=Map.groupBy(tournamentMatches.rows,match=>match.group_name);const groupModal=[...grouped.entries()].map(([name,rows])=>({name,matches:rows.map(match=>({id:match.id,teams:`${match.home_name} × ${match.away_name}`,score:`${match.home_score}:${match.away_score}`,time:`${clock(match.start_time)}-${clock(match.end_time)}`}))}));
  return <main className="ref-main"><header className="ref-menu"><UserAccount/></header>{active?<section className="ref-match-card"><h1>{active.pitch_name}</h1><div className="ref-current"><strong className="ref-time">{clock(active.start_time)} - {clock(active.end_time)}</strong><div className="ref-score"><Team team={{name:active.home_name,logo:active.home_logo}}/><b>{active.home_score}:{active.away_score}</b><Team team={{name:active.away_name,logo:active.away_logo}}/></div><Link className="ref-edit" href={`/referee/match/${active.id}`}>Edytuj</Link><form action={finishMatch}><input type="hidden" name="matchId" value={active.id}/><button type="submit">Zakończ mecz</button></form></div><div className="ref-other"><MatchSummary title="Następny mecz" match={next} emptyScore="-:-"/><RefereeMatchesModal matches={upcomingModal}/><MatchSummary title="Poprzedni mecz" match={previous}/><RefereeMatchesModal matches={finishedModal} title="Rozegrane mecze" emptyText="Brak rozegranych meczów"/></div></section>:<section className="ref-no-matches"><h1>{session.user.name}</h1><p>Brak meczów przypisanych do tego sędziego.</p></section>}<RefereeGroupTableModal groups={groupModal}/></main>;
}
function Team({team}:{team:{name:string;logo:string|null}}){return <div className="ref-team"><div>{team.logo?<Image src={`/dks-cup${team.logo}`} alt="" width={64} height={64}/>:null}</div><span>{team.name}</span></div>}
function MatchSummary({title,match,emptyScore}:{title:string;match:MatchRow|null;emptyScore?:string}){return <div className="ref-match-summary"><span>{title}</span><strong>{match?<>{match.home_name} <b>{emptyScore??`${match.home_score}:${match.away_score}`}</b> {match.away_name}</>:"Brak meczu"}</strong></div>}
