services:
  cache:
    container_name: cache
    image: redis:6.0-alpine

  frontend-new:
    container_name: frontend-new
#     depends_on:
#       - proxy
    build:
      context: ./frontend-new
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: 'http://10.10.10.21/backend'
        NEXT_PUBLIC_API_URL: 'http://10.10.10.21/backend'
    environment:
      NODE_ENV: 'production'
      NEXT_PUBLIC_BACKEND_URL: 'http://10.10.10.21/backend'
      NEXT_PUBLIC_API_URL: 'http://10.10.10.21/backend'
      API_INTERNAL_URL: 'http://directus:8055'
      SERVICE_USER_TOKEN: '89xxkKXkc9'

  proxy:
    container_name: proxy
    build: 
      context: ./proxy
      args:
        PROXY_CONF_FILE: './proxy_production.conf'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/certs:/etc/nginx/certs
volumes:
  directus_uploads:
  node_modules:
  pg_database:
