import { redirect,notFound } from "next/navigation";
import { auth } from "@/auth";
import { pool } from "@/lib/db";
import { UserAccount } from "@/components/UserAccount";
import { RefereeMatchEditor } from "@/components/RefereeMatchEditor";
type Row={id:string;pitch:string;start_time:Date;end_time:Date|null;home_score:number;away_score:number;home_name:string;away_name:string;home_logo:string|null;away_logo:string|null};
async function referee(){const session=await auth();if(!session?.user||session.user.role!=="REFEREE")redirect("/");return session;}
const time=(date:Date|null)=>date?date.toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Warsaw"}):"00:00";
async function updateMatch(data:FormData){"use server";const session=await referee();const id=String(data.get("matchId")??"");const current=await pool.query<{start_time:Date}>(`SELECT m.start_time FROM matches m JOIN tournament_referees tr ON tr.tournament_id=m.tournament_id AND tr.user_id=$2 AND ((tr.pitch_id IS NOT NULL AND tr.pitch_id=m.pitch_id) OR (tr.group_id IS NOT NULL AND tr.group_id=m.group_id)) WHERE m.id=$1`,[id,session.user.id]);if(!current.rows[0])return;const date=current.rows[0].start_time.toLocaleDateString("sv-SE",{timeZone:"Europe/Warsaw"});const startClock=String(data.get("startClock")??data.get("startFallback")??"");const endClock=String(data.get("endClock")??data.get("endFallback")??"");const start=new Date(`${date}T${startClock}:00`);const end=new Date(`${date}T${endClock}:00`);const home=Number(data.get("homeScore"));const away=Number(data.get("awayScore"));if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start||!Number.isInteger(home)||!Number.isInteger(away)||home<0||away<0)return;await pool.query(`UPDATE matches SET start_time=$1,end_time=$2,home_score=$3,away_score=$4,status=CASE WHEN status='scheduled' THEN 'live'::match_status ELSE status END,updated_at=now() WHERE id=$5`,[start,end,home,away,id]);redirect("/referee");}
export default async function MatchEditPage({params}:{params:Promise<{id:string}>}){const session=await referee();const{id}=await params;const result=await pool.query<Row>(`SELECT m.id,p.name pitch,m.start_time,m.end_time,m.home_score,m.away_score,ht.name home_name,at.name away_name,ht.logo_url home_logo,at.logo_url away_logo FROM matches m JOIN pitches p ON p.id=m.pitch_id JOIN teams ht ON ht.id=m.home_team_id JOIN teams at ON at.id=m.away_team_id JOIN tournament_referees tr ON tr.tournament_id=m.tournament_id AND tr.user_id=$2 AND ((tr.pitch_id IS NOT NULL AND tr.pitch_id=m.pitch_id) OR (tr.group_id IS NOT NULL AND tr.group_id=m.group_id)) WHERE m.id=$1`,[id,session.user.id]);const match=result.rows[0];if(!match)notFound();return (<main className="ref-main ref-edit-page"><header className="ref-menu"><UserAccount/></header><RefereeMatchEditor match={{id:match.id,pitch:match.pitch,start:time(match.start_time),end:time(match.end_time),homeScore:match.home_score,awayScore:match.away_score,home:{name:match.home_name,logo:match.home_logo},away:{name:match.away_name,logo:match.away_logo}}} action={updateMatch}/></main>);}
